### PR TITLE
editorial + sec/priv sections rewrite + howto rewrite

### PR DESCRIPTION
**Pull request by samuelweiler**
Lots of editorial stuff.

Added disability status to sensitive information.

Big rewrite of "how to use this doc" and the README to reflect different PING & sec review wish (in-line sections) v. TAG's wish (the verbatim questionnaire).

Notable rewrite of 2.15 (sec/priv considerations sectionS - now separate).  Of note, removed a numbered list of items that should be elsewhere in this doc:
1. Fingerprinting risk;
1. Unexpected exfiltration of data through abuse of sensors;
1. Unexpected usage of the specification / feature by third parties;
1. If the specification includes identifiers, the authors must document what
    rotation period was selected for the identifiers and why.
1. If the specification introduces new state to the user agent, the authors
    must document what guidance regarding clearing said storage was given and
    why.
1. There should be a clear description of the residual risk to the user
    after the privacy mitigations has been implemented.

***
<a href="https://pr-preview.s3.amazonaws.com/samuelweiler/security-questionnaire/pull/103.html" title="Last updated on Sep 24, 2020, 10:45 PM UTC (c8293bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/security-questionnaire/103/5c235b2...samuelweiler:c8293bd.html" title="Last updated on Sep 24, 2020, 10:45 PM UTC (c8293bd)">Diff</a>

### CODE REVIEW

**Review by torgo — APPROVED** [review]
I'm broadly OK with this. I'm concerned that some of these changes have added a lot of text to the document and may therefore reduce the readability. Hopefully that can be addressed in a general editorial pass.

**Review by hober — APPROVED** [review]
This looks good to me. I'm sympathetic to @torgo's concern, and I think we can address that during the general readability editing pass we're in the middle of.

**Comment by samuelweiler** [comment]
@torgo at least I shortened 2.15 by a fair bit?  :-)

**Comment by hober** [comment]
@pes10k and I looked at this during the TAG F2F this week. He approved the merge, and I merged it.

**Pull request merged**
