### PR TITLE
Fix line breaks

### PR DESCRIPTION
**Pull request by jasonanovak**
As part of the PING review of the questionnaire, we noticed that the line breaks were incorrect and not consistently at 80 characters.  To assist in further reviews and edits, went through the Introduction and Threat Models sections and just made sure line breaks were consistent at 80 characters.  No text was changed in this PR.

### CODE REVIEW

**Comment by lknik** [comment]
I'm totally ok with that. Only one thing, what do we do with (https://github.com/w3ctag/security-questionnaire/commit/0177d23369c515caf090989a05e545d46ea04199) if any?

**Comment by jasonanovak** [comment]
I thought 0177d23 had already been merged into master. I think PING will have some additional edits on top of it regardless.

**Comment by lknik** [comment]
Hello,

Was it all merged indeed?

pon., 1 paź 2018 o 14:12 Jason A. Novak <notifications@github.com>
napisał(a):

**Comment by jasonanovak** [comment]
The version of the doc posted at https://w3ctag.github.io/security-questionnaire/ does have the new introduction from 0177d23 for what it’s worth.

J

**Comment by jasonanovak** [comment]
Due to the merging of the PR problem resulting in an auto-forwarding to this PR, I'm going to close this and issue two new PRs: one that handles just the fixing of the line breaks and one that handles the week two edits.

**Pull request closed without merging**
